const common = {
  yearView: 'Year', exportBurnedCsv: 'Export burned calories (CSV)', importBurnedCsv: 'Import burned calories (CSV)',
  burnedCsvHint: 'Backup total, active and resting calories. Import replaces matching dates; other days remain unchanged.',
  importBurnedConfirm: 'Import {count} days and replace existing values for those dates? {skipped} days without total calories will be skipped.',
  importBurnedDone: 'Daily calories imported.', importBurnedError: 'Invalid CSV. Expected columns: datum, celkove_kcal, aktivne_kcal, pokojove_kcal. No data was changed.',
  noBurnedData: 'No daily burned calories to export.',
};
export const energyCsvTranslations = {
  en: common,
  sk: { yearView: 'Rok', exportBurnedCsv: 'Export spálených (CSV)', importBurnedCsv: 'Import spálených (CSV)', burnedCsvHint: 'Záloha celkových, aktívnych a pokojových kalórií. Import prepíše rovnaké dátumy, ostatné dni ponechá.', importBurnedConfirm: 'Importovať {count} dní a prepísať existujúce hodnoty pre tieto dátumy? Dni bez celkových kalórií sa vynechajú: {skipped}.', importBurnedDone: 'Denné kalórie boli importované.', importBurnedError: 'Neplatné CSV. Očakávané stĺpce: datum, celkove_kcal, aktivne_kcal, pokojove_kcal. Údaje sa nezmenili.', noBurnedData: 'Nie sú uložené spálené kalórie na export.' },
  cs: { yearView: 'Rok', exportBurnedCsv: 'Export spálených (CSV)', importBurnedCsv: 'Import spálených (CSV)', burnedCsvHint: 'Záloha celkových, aktivních a klidových kalorií. Import přepíše stejné datumy, ostatní dny ponechá.', importBurnedConfirm: 'Importovat {count} dní a přepsat existující hodnoty? Dny bez celkových kalorií budou vynechány: {skipped}.', importBurnedDone: 'Denní kalorie byly importovány.', importBurnedError: 'Neplatné CSV. Očekávané sloupce: datum, celkove_kcal, aktivne_kcal, pokojove_kcal. Data se nezměnila.', noBurnedData: 'Nejsou uložené spálené kalorie k exportu.' },
  de: { yearView: 'Jahr', exportBurnedCsv: 'Verbrauch exportieren (CSV)', importBurnedCsv: 'Verbrauch importieren (CSV)', burnedCsvHint: 'Sichert Gesamt-, Aktiv- und Ruhekalorien. Gleiche Datumswerte werden ersetzt, andere Tage bleiben erhalten.', importBurnedConfirm: '{count} Tage importieren und vorhandene Werte ersetzen? {skipped} Tage ohne Gesamtkalorien werden übersprungen.', importBurnedDone: 'Tägliche Kalorien importiert.', importBurnedError: 'Ungültige CSV. Spalten: datum, celkove_kcal, aktivne_kcal, pokojove_kcal. Keine Daten geändert.', noBurnedData: 'Keine Verbrauchsdaten zum Exportieren.' },
  es: { yearView: 'Año', exportBurnedCsv: 'Exportar gasto (CSV)', importBurnedCsv: 'Importar gasto (CSV)', burnedCsvHint: 'Copia de calorías totales, activas y en reposo. Reemplaza las fechas coincidentes y conserva los demás días.', importBurnedConfirm: '¿Importar {count} días y reemplazar los valores existentes? Se omitirán {skipped} días sin calorías totales.', importBurnedDone: 'Calorías diarias importadas.', importBurnedError: 'CSV no válido. Columnas: datum, celkove_kcal, aktivne_kcal, pokojove_kcal. No se modificaron datos.', noBurnedData: 'No hay calorías quemadas para exportar.' },
  fr: { yearView: 'Année', exportBurnedCsv: 'Exporter les dépenses (CSV)', importBurnedCsv: 'Importer les dépenses (CSV)', burnedCsvHint: 'Sauvegarde des calories totales, actives et au repos. Remplace les dates correspondantes et conserve les autres jours.', importBurnedConfirm: 'Importer {count} jours et remplacer les valeurs existantes ? {skipped} jours sans calories totales seront ignorés.', importBurnedDone: 'Calories quotidiennes importées.', importBurnedError: 'CSV invalide. Colonnes : datum, celkove_kcal, aktivne_kcal, pokojove_kcal. Aucune donnée modifiée.', noBurnedData: 'Aucune dépense calorique à exporter.' },
  it: { yearView: 'Anno', exportBurnedCsv: 'Esporta consumo (CSV)', importBurnedCsv: 'Importa consumo (CSV)', burnedCsvHint: 'Backup delle calorie totali, attive e a riposo. Sostituisce le date corrispondenti e conserva gli altri giorni.', importBurnedConfirm: 'Importare {count} giorni e sostituire i valori esistenti? Verranno saltati {skipped} giorni senza calorie totali.', importBurnedDone: 'Calorie giornaliere importate.', importBurnedError: 'CSV non valido. Colonne: datum, celkove_kcal, aktivne_kcal, pokojove_kcal. Nessun dato modificato.', noBurnedData: 'Nessuna caloria bruciata da esportare.' },
  pl: { yearView: 'Rok', exportBurnedCsv: 'Eksport spalonych (CSV)', importBurnedCsv: 'Import spalonych (CSV)', burnedCsvHint: 'Kopia kalorii całkowitych, aktywnych i spoczynkowych. Zastępuje zgodne daty i zachowuje pozostałe dni.', importBurnedConfirm: 'Importować {count} dni i zastąpić istniejące wartości? Pominięte dni bez całkowitych kalorii: {skipped}.', importBurnedDone: 'Zaimportowano dzienne kalorie.', importBurnedError: 'Nieprawidłowy CSV. Kolumny: datum, celkove_kcal, aktivne_kcal, pokojove_kcal. Dane nie zostały zmienione.', noBurnedData: 'Brak spalonych kalorii do eksportu.' },
};

const importDataLabels = { en: 'Import data CSV', sk: 'Import dát CSV', cs: 'Import dat CSV', de: 'Daten importieren CSV', es: 'Importar datos CSV', fr: 'Importer des données CSV', it: 'Importa dati CSV', pl: 'Import danych CSV' };
for (const [language, label] of Object.entries(importDataLabels)) energyCsvTranslations[language].importDataBtn = label;
